BBBBBBB BBBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXXX
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBXXXXXBBBBBBBB

BBBBB BBBBBBB
    XXXXXXXXXXXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB
XXXXXXX