XXXXXXXXX XXXXX
XXXXXX
BBBBBBB BBBBBBBBBBBB
BBBBB BBBBBBBBBBXXXXXBBBBBBBB

BBBBB BBBBBBB
    XXXXXXXXXXXXXXX
    XXXXXXX XXX XXXX XXX XXXX XX XXX XXXXXXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX
    XXXXXXX

BBBBBBBB
XXXXXXX