BBBBBBB BBBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXXX
BBBBB BBBBBBBBBBXXXX XXBBBBBBBB

BBBBB BBBBBBB
    XXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB
XXXXXXX