# Generated by Django 4.0.2 on 2024-03-15 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='/^(0|0098|+98)9(0[1-5]|[1 3]\\d|2[0-2]|9[0-4]|98)\\d{7}$/')]),
        ),
    ]
