# Generated by Django 4.0.2 on 2024-04-06 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
