# Generated by Django 5.0.4 on 2024-05-01 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^(?!(\\d)\x01{3})[13-9]{4}[1346-9][ -]?[013-9]{5}$|^$')], verbose_name='Postal code'),
        ),
    ]
