# Generated by Django 4.0.2 on 2023-10-29 12:57

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('price', models.PositiveIntegerField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('season', models.CharField(choices=[('winter', 'winter'), ('summer', 'summer'), ('fall', 'fall')], max_length=6)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('cover', models.ImageField(blank=True, upload_to='cloth/cloth_covers')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cloths.cloth')),
            ],
        ),
    ]
