# Generated by Django 4.0.2 on 2023-03-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cloths',
            new_name='Cloth',
        ),
    ]
