# Generated by Django 4.0.2 on 2023-12-01 14:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=17, null=True),
        ),
    ]
