# Generated by Django 4.0.2 on 2023-12-05 18:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0002_cloth_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='please write your opinion here'),
        ),
    ]
