# Generated by Django 4.0.2 on 2023-12-05 18:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0003_alter_cloth_sizes_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=17, null=True),
        ),
    ]
