# Generated by Django 4.0.2 on 2023-04-30 02:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0005_alter_cloth_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
