# Generated by Django 4.0.2 on 2024-01-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0005_cloth_sales_alter_cloth_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='لطفا نظر خود را برای ما بنویسید '),
        ),
    ]
