# Generated by Django 4.0.2 on 2024-03-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0006_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='لطغا نظر خود را اینجا بنویسید'),
        ),
    ]
