# Generated by Django 4.0.2 on 2024-03-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0007_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
