# Generated by Django 4.0.2 on 2024-04-05 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0009_alter_cloth_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='inventory',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
