# Generated by Django 4.0.2 on 2024-04-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0010_cloth_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='active',
        ),
    ]
