# Generated by Django 4.0.2 on 2024-04-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0011_remove_cloth_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='category',
            field=models.CharField(blank=True, choices=[('tshirt', 'tshirt'), ('pants', 'pants'), ('jacket', 'jacket'), ('suit', 'suit')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(),
        ),
    ]
