# Generated by Django 4.0.2 on 2024-04-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0013_cloth_slug_alter_cloth_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True),
        ),
    ]
