# Generated by Django 4.0.2 on 2024-04-10 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0014_alter_cloth_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='category',
            field=models.CharField(choices=[('tshirt', 'تیشرت و بلوز'), ('pants', 'شلوار'), ('jacket', 'ژاکت و مانتو'), ('suit', 'کت شلوار (رسمی)'), ('others', 'سایر')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='inventory',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
