# Generated by Django 4.0.2 on 2024-04-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0015_alter_cloth_category_alter_cloth_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
