# Generated by Django 4.0.2 on 2024-04-10 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0016_cloth_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(50000)]),
        ),
    ]
