# Generated by Django 4.0.2 on 2024-04-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0017_alter_cloth_brand_alter_cloth_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='season',
            field=models.CharField(blank=True, choices=[('winter', 'winter'), ('summer', 'summer'), ('fall', 'fall')], max_length=6),
        ),
    ]
