# Generated by Django 4.0.2 on 2024-04-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0018_alter_cloth_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='gender',
            field=models.CharField(choices=[('male', 'مردانه'), ('female', 'زنانه')], max_length=6),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='season',
            field=models.CharField(blank=True, choices=[('winter', 'زمستانی'), ('summer', 'تابستانی'), ('fall', 'پاییزی')], max_length=6),
        ),
    ]
