# Generated by Django 5.0.4 on 2024-04-28 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0020_alter_cloth_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='cloth',
            name='brand',
            field=models.CharField(max_length=100, null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='category',
            field=models.CharField(choices=[('tshirt', 'تیشرت و بلوز'), ('pants', 'شلوار'), ('jacket', 'ژاکت و مانتو'), ('suit', 'کت شلوار (رسمی)'), ('others', 'سایر')], max_length=10, null=True, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='gender',
            field=models.CharField(choices=[('male', 'مردانه'), ('female', 'زنانه')], max_length=6, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(50000)], verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='season',
            field=models.CharField(blank=True, choices=[('winter', 'زمستانی'), ('summer', 'تابستانی'), ('fall', 'پاییزی')], max_length=6, verbose_name='فصل'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='colors', to='cloths.color'),
        ),
    ]
