# Generated by Django 5.0.4 on 2024-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0021_color_alter_cloth_brand_alter_cloth_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='colors', to='cloths.color'),
        ),
    ]
