# Generated by Django 5.0.4 on 2024-04-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0023_showphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowPhoto',
        ),
    ]
