# Generated by Django 5.0.4 on 2024-04-29 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0025_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cloth/cloth_covers', verbose_name='image')),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cloths.cloth')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
