# Generated by Django 5.0.4 on 2024-05-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0026_image_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='sizes',
        ),
        migrations.AddField(
            model_name='cloth',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes', to='cloths.size'),
        ),
    ]
